"""Generate the agent-readable itinerary, or check that it is current."""

import argparse
import html
import re
from pathlib import Path
from urllib.parse import quote

from render_itinerary import load_data

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "data/itinerary.md"
SOURCE_URL = "https://github.com/lowjootat/vegas-road-trip-2026/raw/refs/heads/main/data/itinerary.json"


def escape(value):
    """Keep source text literal when a Markdown reader renders it."""
    text = str(value).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    text = re.sub(r"([\\`*_\[\]#|~])", r"\\\1", text)
    return text.replace("\n", "\n    ")


def link(label, url):
    target = quote(url, safe=":/?#[]@!$&'()*+,;=%~_-")
    return f"[{escape(label)}](<{target}>)"


def render_reference(data, *, html_output=False):
    lines = []
    text = html.escape if html_output else escape

    def reference(label, url):
        if html_output:
            return f'<a href="{html.escape(url, quote=True)}">{text(label)}</a>'
        return link(label, url)

    def paragraph(value):
        lines.extend([f"<p>{value}</p>" if html_output else value, ""])

    def item(value):
        lines.extend([f"<ul><li>{value}</li></ul>" if html_output else "- " + value, ""])

    def heading(level, text):
        lines.extend([f"<h{level}>{html.escape(text)}</h{level}>" if html_output else "#" * level + " " + escape(text), ""])

    def field(label, value):
        item(f"{label}: {text(str(value))}")

    def fields(obj, pairs):
        for key, label in pairs:
            if key in obj:
                value = obj[key]
                field(label, ", ".join(value) if isinstance(value, list) else value)

    def links(items):
        for entry in items:
            url = data["places"][entry["placeId"]]["mapsUrl"] if "placeId" in entry else entry["url"]
            item(f"{text(entry['kind'])} link: {reference(entry['label'], url)}")

    def photo(value):
        item(f"Photo reference: {reference(value['alt'], value['url'])}")
        if "caption" in value:
            field("Photo caption", value["caption"])

    def note(value, level):
        heading(level, value["title"])
        paragraph(text(value["text"]))
        links(value.get("links", []))

    trip = data["trip"]
    heading(1, trip["title"])
    paragraph("Generated from " + reference("data/itinerary.json", SOURCE_URL) + ". Do not edit this file directly.")
    command = "<code>python3 scripts/build_offline.py</code>" if html_output else "`python3 scripts/build_offline.py`"
    paragraph("To change the trip, edit the authoritative JSON and rebuild with " + command + ". Preserve existing IDs and explicit timezone guidance. Times and durations below are copied from the source, not recalculated.")
    field("Data version", data["version"])
    fields(trip, [
        ("heading", "Route"), ("description", "Description"), ("eyebrow", "Status"),
        ("introduction", "Introduction"), ("startDate", "Start date"), ("endDate", "End date"),
    ])
    for fact in trip["facts"]:
        field(text(fact["title"]), fact["text"])
    photo(trip["hero"])
    note(trip["bookingNotice"], 2)

    for day in data["days"]:
        heading(2, day["title"])
        fields(day, [("id", "Day ID"), ("date", "Date"), ("navigationLabel", "Navigation label"),
                     ("route", "Route"), ("clockGuidance", "Clock guidance")])
        if "photo" in day:
            photo(day["photo"])
        if day.get("solarEvents"):
            heading(3, "Solar events")
            for event in day["solarEvents"]:
                fields(event, [("kind", "Event"), ("at", "Timestamp"), ("text", "Guidance")])
        heading(3, "Activities")
        for activity in day["activities"]:
            heading(4, activity["location"])
            fields(activity, [("id", "Activity ID"), ("time", "Time"), ("duration", "Duration"),
                              ("startAt", "Start timestamp"), ("endAt", "End timestamp"),
                              ("categories", "Categories"), ("placeIds", "Place IDs"),
                              ("descriptionLead", "Description lead"), ("description", "Description"),
                              ("solarNote", "Solar note")])
            links(activity["links"])
            if "photo" in activity:
                photo(activity["photo"])
        if day["notes"]:
            heading(3, "Day notes")
            for entry in day["notes"]:
                note(entry, 4)

    heading(2, trip.get("mapHeading", "Route stops"))
    for stop in data["mapStops"]:
        heading(3, f"{stop['number']}. {data['places'][stop['placeId']]['name']}")
        fields(stop, [("id", "Stop ID"), ("placeId", "Place ID"), ("dayIds", "Day IDs"),
                      ("defaultDayId", "Default day ID"), ("dayLabel", "Day label"),
                      ("time", "Time"), ("summary", "Summary")])

    heading(2, "Places")
    for pid, place in data["places"].items():
        heading(3, place["name"])
        field("Place ID", pid)
        fields(place, [("latitude", "Latitude"), ("longitude", "Longitude")])
        item(reference("Google Maps", place["mapsUrl"]))

    heading(2, "Before departure checklist")
    paragraph("These are the JSON defaults, not saved browser selections.")
    for entry in data["checklist"]:
        if html_output:
            item(f"{text(entry['text'])} (ID: <code>{text(entry['id'])}</code>; default: {'checked' if entry['checked'] else 'unchecked'})")
        else:
            item(f"[{'x' if entry['checked'] else ' '}] {escape(entry['text'])} (ID: `{entry['id']}`)")
    heading(2, "Notes and credits")
    paragraph(text(trip["footer"]))
    result = "\n".join(lines)
    if html_output:
        result = result.replace("</li></ul>\n\n<ul><li>", "</li>\n<li>")
        template = (ROOT / "web/agent-template.html").read_text(encoding="utf-8")
        return template.replace("{{title}}", html.escape(trip["title"])).replace("{{body}}", result)
    return result


def render_markdown(data):
    return render_reference(data)


def render_agent_html(data):
    return render_reference(data, html_output=True)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the committed Markdown is missing or stale")
    args = parser.parse_args()
    result = render_markdown(load_data())
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != result:
            parser.exit(1, "data/itinerary.md is missing or stale. Run python3 scripts/render_markdown.py and commit the result.\n")
        print("Itinerary Markdown is current")
    else:
        OUTPUT.write_text(result, encoding="utf-8")
        print(f"Generated {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
