"""Generate the agent-readable itinerary, or check that it is current."""

import argparse
import re
from pathlib import Path
from urllib.parse import quote

from render_itinerary import load_data

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "data/itinerary.md"
SOURCE_URL = "https://github.com/lowjootat/vegas-road-trip-2026/raw/refs/heads/main/data/itinerary.json"


def escape(value):
    """Keep source text literal when a Markdown reader renders it."""
    text = str(value).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    text = re.sub(r"([\\`*_\[\]#|~])", r"\\\1", text)
    return text.replace("\n", "\n    ")


def link(label, url):
    target = quote(url, safe=":/?#[]@!$&'()*+,;=%~_-")
    return f"[{escape(label)}](<{target}>)"


def render_markdown(data):
    lines = []

    def heading(level, text):
        lines.extend(["#" * level + " " + escape(text), ""])

    def field(label, value):
        lines.extend([f"- {label}: {escape(value)}", ""])

    def fields(obj, pairs):
        for key, label in pairs:
            if key in obj:
                value = obj[key]
                field(label, ", ".join(value) if isinstance(value, list) else value)

    def links(items):
        for item in items:
            url = data["places"][item["placeId"]]["mapsUrl"] if "placeId" in item else item["url"]
            lines.extend([f"- {escape(item['kind'])} link: {link(item['label'], url)}", ""])

    def photo(value):
        lines.extend([f"- Photo reference: {link(value['alt'], value['url'])}", ""])
        if "caption" in value:
            field("Photo caption", value["caption"])

    def note(value, level):
        heading(level, value["title"])
        lines.extend([escape(value["text"]), ""])
        links(value.get("links", []))

    trip = data["trip"]
    heading(1, trip["title"])
    lines.extend([
        "Generated from " + link("data/itinerary.json", SOURCE_URL) + ". Do not edit this file directly.",
        "",
        "To change the trip, edit the authoritative JSON and rebuild with `python3 scripts/build_offline.py`. Preserve existing IDs and explicit timezone guidance. Times and durations below are copied from the source, not recalculated.",
        "",
    ])
    field("Data version", data["version"])
    fields(trip, [
        ("heading", "Route"), ("description", "Description"), ("eyebrow", "Status"),
        ("introduction", "Introduction"), ("startDate", "Start date"), ("endDate", "End date"),
    ])
    for fact in trip["facts"]:
        field(escape(fact["title"]), fact["text"])
    photo(trip["hero"])
    note(trip["bookingNotice"], 2)

    for day in data["days"]:
        heading(2, day["title"])
        fields(day, [("id", "Day ID"), ("date", "Date"), ("navigationLabel", "Navigation label"),
                     ("route", "Route"), ("clockGuidance", "Clock guidance")])
        if "photo" in day:
            photo(day["photo"])
        if day.get("solarEvents"):
            heading(3, "Solar events")
            for event in day["solarEvents"]:
                fields(event, [("kind", "Event"), ("at", "Timestamp"), ("text", "Guidance")])
        heading(3, "Activities")
        for activity in day["activities"]:
            heading(4, activity["location"])
            fields(activity, [("id", "Activity ID"), ("time", "Time"), ("duration", "Duration"),
                              ("startAt", "Start timestamp"), ("endAt", "End timestamp"),
                              ("categories", "Categories"), ("placeIds", "Place IDs"),
                              ("descriptionLead", "Description lead"), ("description", "Description"),
                              ("solarNote", "Solar note")])
            links(activity["links"])
            if "photo" in activity:
                photo(activity["photo"])
        if day["notes"]:
            heading(3, "Day notes")
            for item in day["notes"]:
                note(item, 4)

    heading(2, trip.get("mapHeading", "Route stops"))
    for stop in data["mapStops"]:
        heading(3, f"{stop['number']}. {data['places'][stop['placeId']]['name']}")
        fields(stop, [("id", "Stop ID"), ("placeId", "Place ID"), ("dayIds", "Day IDs"),
                      ("defaultDayId", "Default day ID"), ("dayLabel", "Day label"),
                      ("time", "Time"), ("summary", "Summary")])

    heading(2, "Places")
    for pid, place in data["places"].items():
        heading(3, place["name"])
        field("Place ID", pid)
        fields(place, [("latitude", "Latitude"), ("longitude", "Longitude")])
        lines.extend(["- " + link("Google Maps", place["mapsUrl"]), ""])

    heading(2, "Before departure checklist")
    lines.extend(["These are the JSON defaults, not saved browser selections.", ""])
    for item in data["checklist"]:
        lines.extend([f"- [{'x' if item['checked'] else ' '}] {escape(item['text'])} (ID: `{item['id']}`)", ""])
    heading(2, "Notes and credits")
    lines.extend([escape(trip["footer"]), ""])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the committed Markdown is missing or stale")
    args = parser.parse_args()
    result = render_markdown(load_data())
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != result:
            parser.exit(1, "data/itinerary.md is missing or stale. Run python3 scripts/render_markdown.py and commit the result.\n")
        print("Itinerary Markdown is current")
    else:
        OUTPUT.write_text(result, encoding="utf-8")
        print(f"Generated {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
